apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-express
    namespace: my-namespace
    labels:
        app: mongo-express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo-express
    template:
        metadata:
            labels:
                app: mongo-express
        spec:
            containers:
                - name: mongo-express
                  image: mongo-express
                  ports:
                      - containerPort: 8081
                  env:
                      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: username
                      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: password
                      - name: ME_CONFIG_MONGODB_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: mongo
                                key: database-url
                      - name: ME_CONFIG_MONGODB_PORT
                        value: '80'
---
apiVersion: v1
kind: Service
metadata:
    name: mongo-express
    namespace: my-namespace
spec:
    selector:
        app: mongo-express
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8081
          nodePort: 30002
