FROM golang:1.17-alpine as build

WORKDIR /app/
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/main ./cmd/main.go


FROM scratch

COPY --from=build /app/build/main /
CMD [ "/main" ]
