apiVersion: v1
kind: Secret
metadata:
    name: mongo
type: Opaque
data:
    # my-nice-username
    username: bXktbmljZS11c2VybmFtZQ==
    # mY-h4(Rd)_-P@$$w0(rD)
    password: bVktaDQoUmQpXy1QQCQkdzAockQp
