apiVersion: apps/v1
kind: Deployment
metadata:
    name: express
    labels:
        app: express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            containers:
                - name: express
                  image: mongo-express
                  ports:
                      - containerPort: 8081
                  env:
                      - name: ME_CONFIG_BASICAUTH_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: express-username
                      - name: ME_CONFIG_BASICAUTH_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: express-password
                      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: mongodb-username
                      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: mongodb-password
                      - name: ME_CONFIG_MONGODB_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: mongo
                                key: mongodb-host
                      - name: ME_CONFIG_MONGODB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: mongo
                                key: mongodb-port
---
apiVersion: v1
kind: Service
metadata:
    name: express
spec:
    type: NodePort
    selector:
        app: express
    ports:
        - protocol: TCP
          nodePort: 30000
          port: 8081
          targetPort: 8081
