apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-express
    labels:
        app: mongo-express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo-express
    template:
        metadata:
            labels:
                app: mongo-express
        spec:
            containers:
                - name: mongo-express
                  image: mongo-express
                  ports:
                      - containerPort: 8081
                  env:
                      - name: ME_CONFIG_BASICAUTH_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: express-username
                      - name: ME_CONFIG_BASICAUTH_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: express-password
                      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: mongodb-username
                      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongo
                                key: mongodb-password
                      - name: ME_CONFIG_MONGODB_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: mongo
                                key: mongodb-host
                      - name: ME_CONFIG_MONGODB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: mongo
                                key: mongodb-port
---
apiVersion: v1
kind: Service
metadata:
    name: mongo-express
spec:
    type: LoadBalancer
    selector:
        app: mongo-express
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30000
