FROM golang:1.17-alpine as build

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app/

COPY ./go.* ./
RUN go mod download

COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/listen/

CMD ["air"]
