apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    # ClusterIP is the default type (does not need to be declared)
    type: ClusterIP
    selector:
        app: nginx
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 80
