[package]
name = "cg"
version = "0.1.0"
edition = "2021"

[unstable]
build-std = ['std', 'panic_abort']

[build]
target = "wasm32-unknown-unknown"
rustflags = '-C target-feature=+atomics,+bulk-memory,+mutable-globals'

[dependencies]
js-sys = "0.3.64"
leptos = "0.3.0"
num-traits = "0.2.15"
wasm-bindgen = "0.2.87"

[dependencies.web-sys]
version = "0.3.64"
features = [
  'CanvasRenderingContext2d',
  'ErrorEvent',
  'Event',
  'ImageData',
  'Navigator',
  'Window',
  'Worker',
  'DedicatedWorkerGlobalScope',
  'MessageEvent',
]
