[serve]
port = 3001
no_autoreload = true

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c",
    "fuser -k 3000/tcp ; node Thunk.proxy.js 3000:3001 Cross-Origin-Opener-Policy:same-origin Cross-Origin-Embedder-Policy:require-corp &",
]
