### kafka rest proxy api

### check availability
GET http://localhost:11100/

### produce events
POST http://localhost:11100/topics/foo
Content-Type: application/vnd.kafka.json.v2+json
Accept: application/vnd.kafka.v2+json

{
    "records": [
        {"key": "jsmith", "value": "alarm clock"},
        {"key": "htanaka","value": "batteries"},
        {"key": "awalther","value": "bookshelves"}
    ]
}

### consume events
### create consumer
curl -X POST \
     -H "Content-Type: application/vnd.kafka.v2+json" \
     --data '{"name": "ci1", "format": "json", "auto.offset.reset": "earliest"}' \
     http://localhost:11100/consumers/cg1

# consumer.instance.timeout.ms detalt 300000ms

### subscribe to topic
curl -X POST \
     -H "Content-Type: application/vnd.kafka.v2+json" \
     --data '{"topics":["foo"]}' \
     http://localhost:11100/consumers/cg1/instances/ci1/subscription

### consume topic
curl -X GET \
     -H "Accept: application/vnd.kafka.json.v2+json" \
     http://localhost:11100/consumers/cg1/instances/ci1/records

### delete consumer (consumers are stateful)
curl -X DELETE \
     -H "Content-Type: application/vnd.kafka.v2+json" \
     http://localhost:11100/consumers/cg1/instances/ci1 
