version: '3.8'

services:
    # mongodb and related services
    mongo:
        image: mongo
        command: mongod --port 10000
        ports:
            - 10000:10000
        volumes:
            - ./database/:/docker-entrypoint-initdb.d/
            - ./database/data/:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: chat
            MONGO_COLLECTIONS: |
                ["user", "message"]
            MONGO_USERS: |
                [{"user": "user", "pwd": "pass"}]
    mongo-ui:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 10999:10999
        environment:
            VCAP_APP_PORT: 10999
            ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:10000/
        depends_on:
            - mongo

    # kafka and related services
    kafka:
        image: confluentinc/cp-kafka:7.0.1
        depends_on:
            - zookeeper
        ports:
            - 11010:11010
        environment:
            KAFKA_BROKER_ID: 0
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:11200
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:11000,HOST://localhost:11010
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    kafka-rest:
        image: confluentinc/cp-kafka-rest:7.0.1
        depends_on:
            - kafka
        ports:
            - 11100:11100
        environment:
            KAFKA_REST_HOST_NAME: kafka-rest
            KAFKA_REST_BOOTSTRAP_SERVERS: DOCKER://kafka:11000
            KAFKA_REST_LISTENERS: http://0.0.0.0:11100
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        ports:
            - 11200:11200
        environment:
            ZOOKEEPER_CLIENT_PORT: 11200
            ALLOW_ANONYMOUS_LOGIN: yes
    kafka-ui:
        image: provectuslabs/kafka-ui
        depends_on:
            - zookeeper
            - kafka
        ports:
            - 11999:11999
        environment:
            SERVER_PORT: 11999
            KAFKA_CLUSTERS_0_NAME: kafka
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:11000
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:11200

    # application containers
    backend:
        build:
            context: ./backend/
            dockerfile: dockerfile
        depends_on:
            - mongo
            - kafka
        ports:
            - 3000:12000
        volumes:
            - ./backend/:/app/
        environment:
            SERVER_PORT: 12000
            KAFKA_BROKERS: kafka:11000
            KAFKA_TOPIC: foo
    frontend:
        build:
            context: ./frontend/
            dockerfile: dockerfile
        depends_on:
            - mongo
            - kafka
        ports:
            - 12001:12001
        volumes:
            - ./frontend/src/:/app/src/
        environment:
            SERVER_PORT: 12001
            VITE_API_ENDPOINT: http://localhost:11100
