binop_separator = "Back"
condense_wildcard_suffixes = true
fn_single_line = true
format_macro_matchers = true
max_width = 120
newline_style = 'Unix'
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = 'Max'
use_try_shorthand = true
