version: '3'

services:
    zookeeper:
        image: 'bitnami/zookeeper:3.7'
        volumes:
            - 'zookeeper-data:/bitnami'
        environment:
            ZOO_SERVER_ID: 0
            ALLOW_ANONYMOUS_LOGIN: yes

    kafka-0:
        image: docker.io/bitnami/kafka:3
        ports:
            - '9090:9080'
        volumes:
            - 'kafka-0-data:/bitnami'
        environment:
            - KAFKA_BROKER_ID=0
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=INTERNAL://:9090,EXTERNAL://:9080
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0:9090,EXTERNAL://localhost:9080
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
        depends_on:
            - zookeeper
    kafka-1:
        image: docker.io/bitnami/kafka:3
        ports:
            - '9091:9081'
        volumes:
            - 'kafka-1-data:/bitnami'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=INTERNAL://:9090,EXTERNAL://:9081
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9090,EXTERNAL://localhost:9081
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
        depends_on:
            - zookeeper
    kafka-2:
        image: docker.io/bitnami/kafka:3
        ports:
            - '9092:9082'
        volumes:
            - 'kafka-2-data:/bitnami'
        environment:
            - KAFKA_BROKER_ID=2
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=INTERNAL://:9090,EXTERNAL://:9082
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-2:9090,EXTERNAL://localhost:9082
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
        depends_on:
            - zookeeper

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        ports:
            - 8080:8080
        depends_on:
            - zookeeper
            - kafka-0
            - kafka-1
            - kafka-2
        environment:
            KAFKA_CLUSTERS_0_NAME: kafka
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9090,kafka-1:9090,kafka-2:9090

volumes:
    zookeeper-data:
        driver: local
    kafka-0-data:
        driver: local
    kafka-1-data:
        driver: local
    kafka-2-data:
        driver: local
