version: '3'

services:
    zookeeper:
        image: 'confluentinc/cp-zookeeper:7.0.1'
        ports:
            - 10000:10000
        environment:
            ZOOKEEPER_CLIENT_PORT: 10000
            ALLOW_ANONYMOUS_LOGIN: yes

    kafka0:
        image: confluentinc/cp-kafka:7.0.1
        depends_on:
            - zookeeper
        ports:
            - 10200:10200
        environment:
            KAFKA_BROKER_ID: 0
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:10000
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka0:10100,HOST://localhost:10200
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    kafka1:
        image: confluentinc/cp-kafka:7.0.1
        depends_on:
            - zookeeper
        ports:
            - 10201:10201
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:10000
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka1:10100,HOST://localhost:10201
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    kafka2:
        image: confluentinc/cp-kafka:7.0.1
        depends_on:
            - zookeeper
        ports:
            - 10202:10202
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:10000
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka2:10100,HOST://localhost:10202
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME:
                DOCKER
                # - ALLOW_PLAINTEXT_LISTENER=yes

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        ports:
            - 8080:8080
        depends_on:
            - zookeeper
            - kafka0
            - kafka1
            - kafka2
        environment:
            KAFKA_CLUSTERS_0_NAME: kafka
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:10000
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:10100,kafka1:10100,kafka2:10100
